# Generated by Django 5.2.5 on 2025-08-09 20:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                (
                    "pages",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non_fiction", "Non-Fiction"),
                            ("mystery", "Mystery"),
                            ("romance", "Romance"),
                            ("sci_fi", "Sci-Fi"),
                            ("biography", "Biography"),
                            ("self_help", "Self Help"),
                            ("history", "History"),
                            ("fantasy", "Fantasy"),
                            ("thriller", "Thriller"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional book cover image",
                        null=True,
                        upload_to="book_covers/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "Want to Read"),
                            ("reading", "Reading"),
                            ("finished", "Finished"),
                        ],
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                (
                    "current_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "books",
                "ordering": ["-created_at"],
            },
        ),
    ]
